### ISSUE TITLE
Missing argument for option: u

### ISSUE THREAD

**Issue by moms-friends-son** [sonatype-nexus-community/circleci-nexus-orb#20]
I'm trying to set up circleCI for maven project and while using orb `nexus-orb: sonatype/nexus-platform-orb@1.0.28` catch error

```
error: Missing argument for option: u
usage: Repository
 -A <key=value>          Asset attributes, can be used multiple times.
                         Example: -Aextension=jar -Aclassifier=bin
 -C <key=value>          Component coordinates, can be used multiple
                         times. Example: -CgroupId=com.example
                         -CartifactId=myapp -Cversion=1.0
 -f,--format <arg>       Artifact format. Examples: maven2
    --filename <arg>     Filename to upload
 -h,--help               Prints this help text
 -p,--password <arg>     Password
 -r,--repository <arg>   Name of target repository on Nexus. Example:
                         maven-releases
    --serverurl <arg>    URL of nexus repository manager server
    --tagname <arg>      The tag to apply (tag must already exist)
 -u,--username <arg>     Username

Exited with code exit status 1
```

My circleCi config file:

```
version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  nexus-orb: sonatype/nexus-platform-orb@1.0.28

workflows:
  main:
    jobs:
      - nexus-orb/nexusjob:
          username: '${NEXUS_USERNAME}'
          password: '${NEXUS_PASSWORD}'
          serverurl: 'https://nexus.dev.********/repository/'
          repository: 'maven-releases/'

```

As I understand I configured all correctly
