### ISSUE TITLE
curl: not found while using nexus-platform-orb/install

### ISSUE THREAD

**Issue by moms-friends-son** [sonatype-nexus-community/circleci-nexus-orb#21]
I'm trying to configure CircleCI on java maven project using this orb.
 This is a config file:
 
```
version: 2.1

orbs:
  maven: circleci/maven@1.3.0
  nexus-platform-orb: sonatype/nexus-platform-orb@1.0.28

jobs:
  install-nexus:
    executor: nexus-platform-orb/nexus-platform-cli
    steps:
      - checkout
      - nexus-platform-orb/install

workflows:
  main:
    jobs:
      - install-nexus
      - nexus-platform-orb/nexusjob:
          context: MyContext
          workspace: tmp/workspace/
          requires:
            - install-nexus
```

But I have an Error:

```
#!/bin/sh -eo pipefail
curl -L https://groovy.jfrog.io/artifactory/libs-release-local/org/codehaus/groovy/groovy-binary/2.5.3/groovy-binary-2.5.3.zip -o apache-groovy-binary.zip
mkdir -p ${CIRCLE_WORKING_DIRECTORY}/sonatype/bin || true
curl -L https://raw.githubusercontent.com/sonatype-nexus-community/docker-nexus-platform-cli/master/src/main/groovy/NexusPublisher.groovy -o ${CIRCLE_WORKING_DIRECTORY}/sonatype/bin/NexusPublisher.groovy
unzip apache-groovy-binary.zip
mv groovy-2.5.3 groovy
echo PATH=${PATH}:${CIRCLE_WORKING_DIRECTORY}/groovy/bin/ > setup.sh

/bin/sh: curl: not found

Exited with code exit status 127
```

Adding:

```
steps:
      - checkout
      - run: apk update && apk add curl curl-dev bash
      - nexus-platform-orb/install
```

Producing one another error:

```
#!/bin/sh -eo pipefail
apk update && apk add curl curl-dev bash
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied

Exited with code exit status 99
```
